export enum SalesStatus {
    CRIADA = 'CRIADA',
    AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',
    PAGA = 'PAGA',
    PAGA_PENDENTE_SYNC = 'PAGA_PENDENTE_SYNC',
    SINCRONIZADA = 'SINCRONIZADA',
    CANCELADA = 'CANCELADA',
}
